#!/bin/sh

while [[ $# -gt 0 ]]; do
  case $1 in
    -d|--dir)
      DIR="$2"
      shift 2;;
    -b|--bucket)
      BUCKET="$2"
      shift 2;;
    -u|--baseurl)
      BASE_URL="$2"
      shift 2;;
    -*|--*)
      echo "Unknown option $1"
      exit 1
      ;;
  esac
done

fswatch -0 -e "^$(echo $DIR)/\." -i "*.(mp4|png|jpg|jpeg)" $DIR | \
  xargs -0 -n 1 -I{} echo "/Users/simon/dev/hellozimi/i.smn.lol/syncd/upload -u $BASE_URL -b $BUCKET \'{}\'" | \
  xargs -I{} sh -c {}
